apiVersion: v1
kind: Service
metadata:
  name: Teketeus
spec:
  selector:
    app: Teketeus
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
